sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: DRJc6eonWcQBbnmsd9HrOVB7ema05s7hq1sAmRcr0VFr+5tkYw6m9lHUkg5cszHg9P/tNSJ8WHnEsLA/V9jfqjuRsoma2yoWBiyBsTGDSQEkmEPj/MzHD1AUjnUdf5A5FGaHHtK8AZzngMsgkf1/NEjE/Ei92jNQLyR/8/ADAX8wZ77dv5FJjAnzsDgrDxh00mJDpX36wny9ASdhRN+dNTPJLn/CqeLVuIjHN9m59CZCl4HlY8pY/CawPU6fRBsDfGVJhTmD7EQZv2VaMy+B4IUKub9UEZQ+w6IyIdITm4VCfynW1lwRg2xgUY6ezSyF352LUWywqGzLX5WTbDG9cts++e/7QlWtYtcHL52HIKxY7dJn/citsvDNQEAJc3NHw4IfvMia1qD+72iF1yqVWovY28vNK8+b/gdG6JHw6WbBDji/ZgtdbNYxY2O26D6fJ27/pggp8GxB2FTD9DB3QQwqSUWaWkTzsvnz89RYw4++14OhS9WvfhFyOywlKT0ugaqkFAlZZ/HJGTRwEBeYTpjxLhIY340pEhnHCfM2BVy2jGMdN1BygdUtAL9jgwPCZ9MvTCFt4YRk9vWujFQduh36h8GvYZrPeTud//wt3+FUArrI+I4BNIyPSME44ROX3/ZtRnYJUjQLM/o9HSo0ejTSUiTKhi9nOhNU3W0+fqU=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Sunday-Under-Three-Heads_922
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy